# Generated by Django 2.2.5 on 2019-09-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTime', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
