# Generated by Django 2.2.5 on 2019-10-01 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTime', '0004_auto_20190930_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='FinishTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
