# Generated by Django 2.2.5 on 2019-10-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTime', '0005_job_finishtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='FinishTime',
            new_name='finish_time',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='InitialTime',
            new_name='initial_time',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='jobbox',
            old_name='InitialTime',
            new_name='initialTime',
        ),
        migrations.RenameField(
            model_name='jobbox',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='BoxId',
        ),
    ]
