# Generated by Django 3.1 on 2025-09-07 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTime', '0006_auto_20191002_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-start_time'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobbox',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Package', 'verbose_name_plural': 'Job Packages'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='initial_time',
        ),
        migrations.RemoveField(
            model_name='jobbox',
            name='initialTime',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When the job ended (leave blank if ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this job has been completed'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_box',
            field=models.ForeignKey(blank=True, help_text='Optional job package this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ManageTime.jobbox'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the job started'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobbox',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this job package was created'),
        ),
        migrations.AddField(
            model_name='jobbox',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this job package is currently active'),
        ),
        migrations.AddField(
            model_name='jobbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Enter a descriptive title for this job', max_length=120, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='jobbox',
            name='title',
            field=models.CharField(help_text='Enter a descriptive title for the job package', max_length=120, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
