# Generated by Django 2.2.5 on 2019-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_job_jobbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='BoxId',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='Title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='jobbox',
            name='Title',
            field=models.CharField(max_length=120),
        ),
    ]
